### ISSUE TITLE
点击文字Bubble里的网址、电话等加蓝信息的回调重载在哪里？

### ISSUE THREAD

**Issue by chenweiyj** [xhzengAIB/MessageDisplayKit#143]
我想请教下，如何才能使点击文字Bubble里的网址、电话等加蓝信息有反应？

谢谢

**Comment by xhzengAIB** [comment]
@chenweiyj 
你好！我错过了这个issue，望谅解，现在你知道怎么做了吗？
在SECoreText里面可以设置这样的高亮属性
