### ISSUE TITLE
自定义消息列表的View

### ISSUE THREAD

**Issue by xhzengAIB** [xhzengAIB/MessageDisplayKit#168]
通过Delegate的方式进行回调分发

**Comment by plusmancn** [comment]
先看下代码

**Comment by plusmancn** [comment]
Customize your cells?

    - (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
    {
        JSQMessagesCollectionViewCell *cell = (JSQMessagesCollectionViewCell *)[super collectionView:collectionView cellForItemAtIndexPath:indexPath];

        // Customize the shit out of this cell
        // See the docs for JSQMessagesCollectionViewCell

        return cell;
    }

JSQMessagesViewController 已经支持了。

**Comment by xhzengAIB** [comment]
嗯！可以这么认为，JSQMessagesViewController支持的扩展比这个库好很多，而且最近发现东西没有重构，导致没跟上国际的大神，还望你多多包含。

**Comment by xhzengAIB** [comment]
我这里是打算使用Delegate的方式来定制，而不是用继承的方式

**Comment by xhzengAIB** [comment]
如果采用继承的方式，可以达到与之前的使用方法类似，也可以采取，希望后续能提供多种方式。

**Comment by plusmancn** [comment]
容我先研究下，JSQMessages
