### ISSUE TITLE
发送图片时候报 CGBitmapContextCreate CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 32 bits/pixel 错误

### ISSUE THREAD

**Issue by plusmancn** [xhzengAIB/MessageDisplayKit#173]
<Error>: CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 32 bits/pixel; 3-component color space; kCGImageAlphaLast; 960 bytes/row.
Jan  4 15:35:27 PlusMan.lan JuHappy[23807] <Error>: CGContextConcatCTM: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by xhzengAIB** [comment]
是不是程序已经crash了？

**Comment by DaidoujiChen** [comment]
先關注, 這也許跟 https://github.com/xhzengAIB/MessageDisplayKit/commit/81823a8b6a27139fa23a46b3ff8315da2936ae63 有些類似.

**Comment by plusmancn** [comment]
没有crash，还是能跑的，是图片格式处理时候的问题，新版 ios 8 才会报错。

**Comment by xhzengAIB** [comment]
应该是类似的问题，陈大哥知道怎么回事，上次是他帮忙解决的   @DaidoujiChen

**Comment by DaidoujiChen** [comment]
Hello all,

我用目前最新的版本 build 出來沒有發現問題說, 我測試了幾張不同 size 的圖片, 都沒有發生這個錯誤

![2015-01-12 10 00 30](https://cloud.githubusercontent.com/assets/670441/5698167/06023adc-9a42-11e4-882d-0fbb7c6fb053.png)

是從 "首頁" -> "任一個人名" -> "按 + 選擇要傳送的項目" -> "相片" -> "選隨便一張"

這樣重現嗎?

**Comment by xhzengAIB** [comment]
应该图片的URL失效了，导致空图片，所以这个问题注意一下https://github.com/xhzengAIB/MessageDisplayKit/commit/81823a8b6a27139fa23a46b3ff8315da2936ae63
