### ISSUE TITLE
真机调试联系人页面右侧字母导航显示不完全，设备是iPhone4，ios7系统

### ISSUE THREAD

**Issue by iosHot** [xhzengAIB/MessageDisplayKit#175]
如下图：
![image](https://cloud.githubusercontent.com/assets/8704204/5678368/a7561786-982c-11e4-8d4f-7cccc9df83e1.png)

**Comment by xhzengAIB** [comment]
好像是哦！  不过这个只是Example里面的一个业务，你可以套自己的界面的哦！   你能解决这个问题吗？   欢迎你PR

**Comment by xhzengAIB** [comment]
@molon 
molon能否帮忙看看啊？

**Comment by molon** [comment]
@xhzengAIB 这个index应该是用的系统框架里tableView 默认的那个，不是多选界面的。而这个显示不完全是正常的，显示完全还不正常了，因为apple默认会对字母有个最小高度，低于最小高度就会进行重叠，这是很合理的。

**Comment by xhzengAIB** [comment]
ok！明白了  意思是把一些隐藏了对吗？

**Comment by molon** [comment]
@xhzengAIB 对的，他这个体现的不直观，搞个更小高度的tableView会直观很多。:)

**Comment by xhzengAIB** [comment]
谢谢Molon的解答
