### ISSUE TITLE
消息TableView的vertical indicator起始点有问题

### ISSUE THREAD

**Issue by hanchunlong** [xhzengAIB/MessageDisplayKit#180]
![48f86593-5447-4d6d-bc07-d3d7f5cc21dc](https://cloud.githubusercontent.com/assets/2275168/5887130/e716e996-a3f2-11e4-874b-6c140f4882b0.png)
我自己的Demo使用了auto layout，当我向下拉消息页面，发现tableview的 indicator顶部起始位置居然在导航栏下64 points距离。如图

怀疑是设置messageTableView.scrollIndicatorInsets或者messageTableView.contentInset的问题，就查询了下代码。inset的top是在这里赋值的，注释后运行发现OK了。对这块不熟悉（autolayout和uiscrollview结合），提交issue你给看下先。
```obj-c
- (UIEdgeInsets)tableViewInsetsWithBottomValue:(CGFloat)bottom {
    UIEdgeInsets insets = UIEdgeInsetsZero;
    
    if ([self respondsToSelector:@selector(topLayoutGuide)]) {
        insets.top = 64;//如果注释这里的top设置，在autolayout情况下，messageTableView的indicator起始点就OK
    }
    
    insets.bottom = bottom;
    
    return insets;
}
```

**Comment by xhzengAIB** [comment]
因为有些项目可能直接使用
````objc
    self.edgesForExtendedLayout = UIRectEdgeNone;
`````
这个时候，这句话需要这样做吗？

**Comment by hanchunlong** [comment]
```objc
self.edgesForExtendedLayout = UIRectEdgeNone;
```
这个对于我的Demo没产生期望的效果。我的demo是用的storyboard，并且使用了autolayout和size class，只有这个聊天页面没有在storyboard中创建，而是需要的时候代码创建并push出来的。

看了下苹果的文档，关于toplayoutguide这么介绍的：
>   * The bottom of the navigation bar, if a navigation bar is visible
>   * The bottom of the status bar, if only a status bar is visible
>   * The top edge of the view controller's view, if neither a status bar nor navigation bar is visible
> If a container navigation controller's navigation bar is visible and opaque, the navigation controller lays out the frontmost view controller's view so its top edge abuts the bottom of the navigation bar. In this case, the value of this property is 0. 
上面三条已经说明toplayoutguide的位置，是自动根据是否使用status bar 或者nav bar来判断的。但同时也说明：如果container的nav是visible and opaque，那么toplayoutguide的length就直接是0了. `我想我的demo应该就是这个情况了,translucent属性是NO! 我这里如果将本应该是0的toplayoutguide改成64反而不对了`

**Comment by xhzengAIB** [comment]
```obj-c
- (UIEdgeInsets)tableViewInsetsWithBottomValue:(CGFloat)bottom {
    UIEdgeInsets insets = UIEdgeInsetsZero;
    
    if ([self respondsToSelector:@selector(topLayoutGuide)]) {
        insets.top = self.toplayoutguide. length;//如果注释这里的top设置，在autolayout情况下，messageTableView的indicator起始点就OK，而不是写死固定的64吗？
    }
    
    insets.bottom = bottom;
    
    return insets;
}
```

**Comment by hanchunlong** [comment]
对，让messageTableView所在的UIViewController给出inset的top值。
```obj-c
insets.top = self.topLayoutGuide.length;
```

我这里的iOS8 storyboard+autolayout+size class是OK的，其他的未测

**Comment by xhzengAIB** [comment]
不知道在iOS6上的效果是如何的呢？能否帮忙也测试一下呢？

**Comment by xhzengAIB** [comment]
我测试过后，写死64确实是个不对的事情，因为在topLayoutGuide中，length可能为0，也可能为64.

**Comment by xhzengAIB** [comment]
采纳这个想法
