### ISSUE TITLE
XHMessageTableViewController 崩溃

### ISSUE THREAD

**Issue by qylibohao** [xhzengAIB/MessageDisplayKit#181]
navigation controller push 进入XHMessageTableViewController，手势右划返回出现错误。

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    
    if (self.textViewInputViewType != XHInputViewTypeNormal) {
        [self layoutOtherMenuViewHiden:YES];
    }
    
    // remove键盘通知或者手势
    [self.messageTableView disSetupPanGestureControlKeyboardHide:self.allowsPanToDismissKeyboard];
    
    // remove KVO
    //崩溃语句
    [self.messageInputView.inputTextView removeObserver:self forKeyPath:@"contentSize"];
    [self.messageInputView.inputTextView setEditable:NO];
}

*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <ChatMessageTableViewController 0x7a861610> for the key path "contentSize" from <XHMessageTextView 0x7ba7c200> because it is not registered as an observer.'

讲removeObserver 语句放到delloc函数下就没有问题，但是出现表情键盘不消失的情况

**Comment by xhzengAIB** [comment]
你是不是把add的代码去掉了？

**Comment by qylibohao** [comment]
我没有去掉add函数

**Comment by qylibohao** [comment]
viewWillDisappear 里面的函数 会在手势返回的过程中触发，是否能够迁移到viewDidDisappear呢

**Comment by qylibohao** [comment]
找到原因了，结贴。重载viewWillAppear了- -！
