### ISSUE TITLE
程序运行报各种错误

### ISSUE THREAD

**Issue by libinai123** [xhzengAIB/MessageDisplayKit#182]
您好，最近在做一个类似朋友圈的功能可是你的demo各种运行不起来 是什么原因呢"_OBJC_CLASS_$_XHDisplayTextViewController", referenced from:
      objc-class-ref in XHDemoWeChatMessageTableViewController.o
  "_OBJC_CLASS_$_XHEmotion", referenced from:

**Comment by xhzengAIB** [comment]
第一，请运行
https://github.com/xhzengAIB/MessageDisplayKit/tree/master/Example/MessageDisplayKitWorkSpace.xcworkspace

第二，你应该了解什么是xcworkspace？

第三，你可能需要更高版本的Xcode

第四，你的Issue标题太笼统

Jack
