### ISSUE TITLE
关于消息样式的拓展性问题，是否提供了拓展接口?

### ISSUE THREAD

**Issue by plusmancn** [xhzengAIB/MessageDisplayKit#183]

**Comment by xhzengAIB** [comment]
你好！你可以关注这个[Issue](https://github.com/xhzengAIB/MessageDisplayKit/issues/168)，
由于工作的太忙，还时间去重构，你是否有兴趣PR呢？

Jack

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/MessageDisplayKit/issues/168

**Comment by plusmancn** [comment]
我先看下代码
