### ISSUE TITLE
研究了半天还是编译不起来的问题

### ISSUE THREAD

**Issue by zengguiyeah** [xhzengAIB/MessageDisplayKit#184]
你好，我按照你说的方法，安装了iOS-Universal-Framework插件，然后重启Xcode，还是报target specifies product type 'com.apple.product-type.framework', but there's no such product type for the 'iphonesimulator' platform，为什么会这样呢，是因为我用的是Xcode5的原因吗
![2015-02-07 10 46 50](https://cloud.githubusercontent.com/assets/4100670/6090524/3ba6de48-aeb7-11e4-9145-73dceb1ddce0.png)

**Comment by xhzengAIB** [comment]
使用xcode6编译一下试试
