### ISSUE TITLE
pod 进去后出现错误

### ISSUE THREAD

**Issue by yuchangtaoyu** [xhzengAIB/MessageDisplayKit#185]
ld: library not found for -lPods-MessageDisplayKit

**Comment by xhzengAIB** [comment]
是不是使用错误了呢？

**Comment by xhzengAIB** [comment]
我这边测试一下，等下给你反馈

**Comment by xhzengAIB** [comment]
你检查一下是不是你的CocoaPods导致的错误，库本身没有问题，测试通过的，下图

![Uploading 73F10AA9-4FB2-4205-8834-736D2345BEFE.png . . .]()

**Comment by xhzengAIB** [comment]
![73f10aa9-4fb2-4205-8834-736d2345befe](https://cloud.githubusercontent.com/assets/1969908/6091821/0a888900-aef9-11e4-83ac-ad34cb935375.png)

**Comment by yuchangtaoyu** [comment]
谢谢，我再看看

**Comment by yuchangtaoyu** [comment]
当我运行 你的那个demo 
![image](https://cloud.githubusercontent.com/assets/1570406/6095966/d334e9a8-afb1-11e4-90fb-ea578aa090ea.png)的时候 发现有这个错误，是怎么回事，谢谢

dyld: Library not loaded: @rpath/MessageDisplayKit.framework/MessageDisplayKit
  Referenced from: /private/var/mobile/Containers/Bundle/Application/F38DD52B-B27B-4C10-8D8E-ED986DA3C2A2/MessageDisplayKitWeChatExample.app/MessageDisplayKitWeChatExample
  Reason: image not found

**Comment by xhzengAIB** [comment]
![668be6cf-1664-4af7-a82f-2c2cbee5a486](https://cloud.githubusercontent.com/assets/1969908/6095997/ed310ba0-afb3-11e4-8128-aeff5161807a.png)

添加MessageDisplayKit.framework
