### ISSUE TITLE
conflicting types for 'nsfont'

### ISSUE THREAD

**Issue by bottotl** [xhzengAIB/MessageDisplayKit#186]
Xcode6.3-Beta 编译项目出现conflicting types for 'nsfont'错误
![qq20150221-1](https://cloud.githubusercontent.com/assets/9837901/6312609/23fdaa02-b9ba-11e4-828d-72ffbcf1a114.png)

**Comment by xhzengAIB** [comment]
我这边还没用xcode6.3进行测试，要不你问问另外一个作者？https://github.com/kishikawakatsumi/SECoreTextView

**Comment by IrenBest** [comment]
XCode 6.2编译也是同样的问题

**Comment by xhzengAIB** [comment]
https://github.com/hoppenichu/SECoreTextView/commit/41480c70e1dbab28b2c79dbc73741aacbebb8e5e

**Comment by Opencil** [comment]
求解决。。

**Comment by Opencil** [comment]
@IrenBest 求问这个问题解决了没。。。

**Comment by bottotl** [comment]
前面我点击过作者给的hoppenichu/SECoreTextView@41480c7，给出了解决方案（我没有试验），现在链接不知道为啥失效了，可以选择去https://github.com/kishikawakatsumi/SECoreTextView下载最新版替换（我这边网速太慢了，还没有下完，等我到时候下完了试试）

**Comment by bottotl** [comment]
那个作者最新的代码是直接把那句出错的去掉了，其他的我也不知道做了什么改动……

**Comment by Opencil** [comment]
thanks a lot.
