### ISSUE TITLE
在xcode6.2下SECompatibility.h编译失败

### ISSUE THREAD

**Issue by suasong** [xhzengAIB/MessageDisplayKit#189]
/Users/tes/Documents/workspace/HX-O2O/mobile/IOS/HX_SHOP_NEW/HX_SHOP/HX_SHOP/MessageDisplayKit/Classes/Vendor/SECoreTextView/SECompatibility.h:15:22: Conflicting types for alias 'NSFont'

SECompatibility.h文件的15行编译报错
@compatibility_alias NSFont UIFont;
在xcode6.1上是ok的，但我升级到6.2了以后就不行了

**Comment by huapeng222** [comment]
同上,下载了最新的代码一样是这个错误

**Comment by xhzengAIB** [comment]
https://github.com/hoppenichu/SECoreTextView/commit/41480c70e1dbab28b2c79dbc73741aacbebb8e5e

**Comment by suasong** [comment]
ok，算是解决了

**Comment by iBenjamin** [comment]
#define NSFont UIFont没用哦，hoppenichu/SECoreTextView的作者更新了最新版解决了这个问题，麻烦华仔也更新下哈。

**Comment by xhzengAIB** [comment]
pod已经更新了

**Comment by junyunuos** [comment]
楼主、能告诉我解决方案嘛

**Comment by lzwjava** [comment]
@junyunuos  https://github.com/xhzengAIB/MessageDisplayKit/commit/bed0a7cccbf31ad7023ba0dac53ae8615802f664

用最新的SECoreTextView 即可，https://github.com/kishikawakatsumi/SECoreTextView

**Comment by suasong** [comment]
@junyunuos 
后来我也是下了新的SECoreTextView全替换掉的
