### ISSUE TITLE
更新 hoppenichu/SECoreTextView

### ISSUE THREAD

**Issue by iBenjamin** [xhzengAIB/MessageDisplayKit#190]
#define NSFont UIFont没用哦，hoppenichu/SECoreTextView的作者更新了最新版解决了这个问题，麻烦华仔也更新下哈。

**Comment by xhzengAIB** [comment]
好的！ 谢谢提醒，我再把他换上去看一下，但是我要测试一下，换了之后现在的功能会不会有影响。

**Comment by iBenjamin** [comment]
麻烦能不能顺便把pod也更新下。。。

**Comment by xhzengAIB** [comment]
@iBenjamin 
好的！ 谢谢提醒

**Comment by xhzengAIB** [comment]
pod已经更新了
