### ISSUE TITLE
使用kAudioFormatMPEG4AAC录音，获取不到时长

### ISSUE THREAD

**Issue by hanchunlong** [xhzengAIB/MessageDisplayKit#193]
使用更常见的aac录制测试的时候发现，如果使用kAudioFormatMPEG4AAC作为AVFormatIDKey。
录音完毕调用getVoiceDuration获取音频时长为0，将文件从沙盒拷贝出来查看并播放都是正常的。进一步看到AVAudioPlayer *play = [[AVAudioPlayer alloc] initWithContentsOfURL:[NSURL fileURLWithPath:recordPath] error:nil];初始化后play为nil
不知何故

**Comment by xhzengAIB** [comment]
这个问题我也留意到了！但是这点很奇怪，之前都是没有问题的！能否帮忙一起找找原因呢？

**Comment by hanchunlong** [comment]
初步定位原因是这样的：你获取时长的时候还没有stopRecording，而压缩格式的aac编码是需要使用到硬件加速功能。此时录音部分已经占用硬件加速，导致AVAudioPlayer针对该压缩语音文件调用硬件加速初始化失败。（这个是根据AAC格式需要硬件加速的要求猜测的）
所以将getVoiceDuration放到了recorder stop之后进行。
非压缩的文件没有这个问题，所以之前用无损格式时不会出现问题。

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/MessageDisplayKit/pull/195
