### ISSUE TITLE
在大段纯英文文本时，SETextView有点偏大

### ISSUE THREAD

**Issue by BOOLRon** [xhzengAIB/MessageDisplayKit#194]
![screen shot 2015-03-19 at 3 38 50 pm](https://cloud.githubusercontent.com/assets/1638964/6726119/236bf122-ce4e-11e4-9e9c-4b907b48d351.png)

![screen shot 2015-03-19 at 3 36 30 pm](https://cloud.githubusercontent.com/assets/1638964/6726121/24a46b5a-ce4e-11e4-9a82-41c2038aa929.png)

**Comment by xhzengAIB** [comment]
@BOOLRon 
谢谢反馈，我测试一下，会不会由于全英文，计算上有偏差呢？你的意思是：文本越长，然后偏差越大吗？

**Comment by BOOLRon** [comment]
不会越来越大，是当长到某一程度，就会有固定的偏差

**Comment by xhzengAIB** [comment]
好的，我仔细检查一下，看看是不是我的问题，你估计是SETextView的问题吗？

**Comment by BOOLRon** [comment]
![screen shot 2015-03-19 at 5 32 39 pm](https://cloud.githubusercontent.com/assets/1638964/6727587/02e5981c-ce5e-11e4-848a-15e19024e5f5.png)
是的，我估计是

**Comment by xhzengAIB** [comment]
我更新了一下！中文的情况下是没有问题了，但是不知道为什么在全英文的情况下是有问题的，能否帮忙看看？

**Comment by BOOLRon** [comment]
赞！完美fix了！

**Comment by xhzengAIB** [comment]
好像在全英文的时候，是没有解决，你试试看，看看能否有解决方案
