### ISSUE TITLE
文本框内如果有换行符，就破相了。

### ISSUE THREAD

**Issue by plusmancn** [xhzengAIB/MessageDisplayKit#200]
![img_2213](https://cloud.githubusercontent.com/assets/4994682/6794545/03c4ddc0-d20e-11e4-80c4-3b8c8619c850.PNG)

**Comment by antony-liu** [comment]
使用组件提供的Demo程序无法重现问题，但在我自己的项目中也出现了这个问题(使用pod管理的组件)。我已经提交了修改，请确认问题是否修复了

**Comment by xhzengAIB** [comment]
我试试看，为什么高度改了之后就行呢？字体大小对应的高度不一样吗？

**Comment by xhzengAIB** [comment]
能否PR一个过来呢？

**Comment by plusmancn** [comment]
问题解决

**Comment by xhzengAIB** [comment]
你不是修改了代码吗？能否PR一个过来呢？我这边就不修改了

**Comment by plusmancn** [comment]
还是有问题的，文本框的宽度，是由首行长度决定的。还要改改。

**Comment by antony-liu** [comment]
重现了，我修改下
![img_0017](https://cloud.githubusercontent.com/assets/1443163/6820045/e7d87772-d305-11e4-8bb6-64f4471e6b30.PNG)

**Comment by plusmancn** [comment]
Done!

**Comment by plusmancn** [comment]
新方法 ios 7 下 会崩溃

**Comment by plusmancn** [comment]
聊天时间戳，在 iPhone6 等大屏手机上不居中。

**Comment by xhzengAIB** [comment]
时间那个不居中我再看看怎么回事

**Comment by Hitooo** [comment]
通过CocoaPods安装的最新版MessageDisplayKit（3.0.2），其中源代码并不是最新的嘛

**Comment by lzwjava** [comment]
可指定 :git => 'https://github.com/xhzengAIB/MessageDisplayKit.git'
