### ISSUE TITLE
怎么增加一个登录页面

### ISSUE THREAD

**Issue by hlm1990** [xhzengAIB/MessageDisplayKit#205]
怎么增加一个登录页面

**Comment by hlm1990** [comment]
怎么增加一个登录页面怎么增加一个登录页面怎么增加一个登录页面怎么增加一个登录页面怎么增加一个登录页面

**Comment by hlm1990** [comment]
实现登录后跳转到消息列表页面 求大神发招

**Comment by xhzengAIB** [comment]
这些是业务需求，开源库将不提供，可以到[这里](http://stackoverflow.com/)提问
