### ISSUE TITLE
关于「我的相册」的实现

### ISSUE THREAD

**Issue by chenweiyj** [xhzengAIB/MessageDisplayKit#206]
![1 pic_hd](https://cloud.githubusercontent.com/assets/1733948/6962595/7653d574-d968-11e4-9ad2-bce3dae73022.jpg)

像微信我的相册这种，一个单元格左边是日期右边是多条记录怎么实现？右边用一个SECoreTextView能实现吗？

**Comment by xhzengAIB** [comment]
那我关闭了？

**Comment by chenweiyj** [comment]
好的。
