### ISSUE TITLE
@compatibility_alias NSFont UIFont; 报冲突错误

### ISSUE THREAD

**Issue by lovelytomy** [xhzengAIB/MessageDisplayKit#209]
SECompatibility.h 这个文件中的@compatibility_alias NSFont UIFont; 报冲突错误：Conflicting types for alias 'NSFont'，我在iOS7.1和iOS8 下测试都报这个错误，xcode版本是6.2，请问需要怎么修改才可以呢

**Comment by xhzengAIB** [comment]
你好！  这个问题已经解决了吧！
看这个[commit](https://github.com/xhzengAIB/MessageDisplayKit/commit/bed0a7cccbf31ad7023ba0dac53ae8615802f664)

**Comment by HalZf** [comment]
今天我也遇到了！正在下载最新版！感谢提供方案！
