### ISSUE TITLE
发送voice的时候，只有点击右边才可以

### ISSUE THREAD

**Issue by cloud-hot** [xhzengAIB/MessageDisplayKit#210]
曾大神，当发送voice的时候，只有点击“按住说话”这个按钮的右边才能够触发发送声音，如果点击左侧的话就没有任何反应，我试验了微信本身的发送voice功能没有这个问题，他的整个按钮点击任意位置都可以触发，希望能够解决这个问题，以提高用户体验，谢谢！

**Comment by xhzengAIB** [comment]
这个问题我在找方案，可能不是触控范围上的，也可能是手势上的冲突。

@hanchunlong

**Comment by hanchunlong** [comment]
self.navigationController.interactivePopGestureRecognizer.delaysTouchesBegan=NO;

**Comment by xhzengAIB** [comment]
@cloud-hot 
这位大神@hanchunlong 已经解决了

**Comment by cloud-hot** [comment]
@xhzengAIB 谢谢了！我回去测试下给回馈

**Comment by cloud-hot** [comment]
测试确认解决了，谢谢两个大神了
