### ISSUE TITLE
加入Framework后，无法启动，虽然已经添加了Resource文件夹

### ISSUE THREAD

**Issue by taojigu** [xhzengAIB/MessageDisplayKit#212]
dyld: Library not loaded: @rpath/MessageDisplayKit.framework/MessageDisplayKit
  Referenced from: /private/var/mobile/Containers/Bundle/Application/404C7103-C542-4BF5-8167-A5A8968A31EC/DoctorXmppClient.app/DoctorXmppClient
  Reason: image not found

**Comment by xhzengAIB** [comment]
这个是xcode新的打包方式导致的，你需要在  project->General->Embedded Binaries 添加framework进去
