### ISSUE TITLE
编译的时候，显示NSFont中没有fontName和pointSize的属性。

### ISSUE THREAD

**Issue by agan112** [xhzengAIB/MessageDisplayKit#217]
文件位置SETextView.m等只要有调用NSFont的地方，显示的问题是：Property 'pointSize' cannot be found in forward class object 'NSFont'
![111](https://cloud.githubusercontent.com/assets/6804996/7223648/d67c69b4-e757-11e4-89af-952ea36ae9b4.png)

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/MessageDisplayKit/issues/189

**Comment by agan112** [comment]
Thank you.
