### ISSUE TITLE
模拟器录音的时候会出现奔溃

### ISSUE THREAD

**Issue by FutureChen** [xhzengAIB/MessageDisplayKit#218]
我新建了一个项目，引用了大神的框架、但是模拟器录音的时候控制台会出现下面这些提示，是不是要设置写什么C++??

[XHMessageTableViewController prepareRecordingVoiceActionWithCompletion:] [Line 1064] prepareRecordingWithCompletion
[XHMessageTableViewController didStartRecordingVoiceAction] [Line 1069] didStartRecordingVoice
 WARNING:   246: Default audio device changed. Restart the simulator to have it use the newly-selected device.
 -[XHMessageTableViewController didStartRecordingVoiceAction] [Line 1069] didStartRecordingVoice
 -[XHMessageTableViewController didFinishRecoingVoiceAction] [Line 1079] didFinishRecoingVoice

**Comment by xhzengAIB** [comment]
不改！  我miss了这个issue，模拟器不是崩溃，你换真机就好了！
