### ISSUE TITLE
发送图片

### ISSUE THREAD

**Issue by cloudPig** [xhzengAIB/MessageDisplayKit#223]
发送的图片有变形，但是没有找到相关设置的代码，能否修改下？

**Comment by xhzengAIB** [comment]
这块好像一直都有问题，我看看怎么修改绘制的代码

**Comment by cloudPig** [comment]
好的，辛苦了。

**Comment by Hitooo** [comment]
发图片时界面会假死，要等一会才会出现刷新的小圆圈，这个太影响使用了，能力有限，还请大神指点一下

**Comment by xhzengAIB** [comment]
@Hitooo 
这个你可以截图，讲讲流程吗？单单文字我可能不会理解的不太清楚呀！

**Comment by CNlichao** [comment]
这个问题发送时好解决，就是收到不好解决，如果可能从message中得到图片大小也是好解决。现在从网络获取图片，有点问题

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/MessageDisplayKit/commit/613e0c4866a18bbd4cfae531673bb4471e88ff7b
