### ISSUE TITLE
快速的连续发送消息会引发crash

### ISSUE THREAD

**Issue by jackiehu** [xhzengAIB/MessageDisplayKit#224]
crash原因不明
- (void)controllerDidChangeContent:(NSFetchedResultsController *)controller {
    [self.messageTableView endUpdates];
}

**Comment by xhzengAIB** [comment]
@jackiehu 
确实有这个问题，在tableview的刷新上做了操作，直接用reloadData就可以了!

**Comment by jackiehu** [comment]
改了也不行,还是会crash,只是crash位置不同罢了

**Comment by xhzengAIB** [comment]
好吧！ 你对这个问题怎么看呢？比如有类似的解决方案吗？

**Comment by jackiehu** [comment]
我也在查,但是毫无头绪啊,最好加一个发消息间隔

**Comment by brasbug** [comment]
NSMutableArray *indexPaths = [NSMutableArray arrayWithCapacity:1];
        [indexPaths addObject:[NSIndexPath indexPathForRow:messages.count - 1 inSection:0]];  注销掉这两句
