### ISSUE TITLE
XHNewsTableViewController 新闻那个怎么添加点击事件

### ISSUE THREAD

**Issue by hlm1990** [xhzengAIB/MessageDisplayKit#226]
XHNewsTableViewController 新闻那个怎么添加点击事件

**Comment by xhzengAIB** [comment]
只需要给view添加手势就好了！

**Comment by xhzengAIB** [comment]
@hlm1990 
因为Cell里面有多个新闻，所以需要在Cell里面找到对应的新闻View进行添加手势，添加手势请参考这里http://stackoverflow.com/questions/6844365/uitapgesturerecognizer
