### ISSUE TITLE
看到 40 个新 commits，是不是可以发布新版了？

### ISSUE THREAD

**Issue by lzwjava** [xhzengAIB/MessageDisplayKit#227]
指定 git 地址，每次pod ，好像都会去clone 项目，所以需要发布来达到缓存的效果，快速 pod install 。

3.0.2 以来，解决了时间戳 在 iphone 6不居中等问题，感觉可以发新版了。

@xhzengAIB

**Comment by xhzengAIB** [comment]
已经发布了！
