### ISSUE TITLE
XHNewsTableViewController有没有插入新消息的接口

### ISSUE THREAD

**Issue by hlm1990** [xhzengAIB/MessageDisplayKit#228]
其他的聊天页面有一个self addMessage 就可以在底部插入一条新消息 XHNewsTableViewController有类似的接口吗

**Comment by xhzengAIB** [comment]
类似的道理，你可以模仿一下！暂时是没有写的，或者你PR？

**Comment by hlm1990** [comment]
能麻烦指导下吗  多谢了  很棒的框架

**Comment by xhzengAIB** [comment]
参考一下这个方法https://github.com/xhzengAIB/MessageDisplayKit/blob/master/MessageDisplayKit/Classes/Controllers/XHMessageTableViewController/XHMessageTableViewController.m#L234

**Comment by hlm1990** [comment]
XHNewsTableViewController本身需要做什么修改或扩展吗

**Comment by xhzengAIB** [comment]
这块不涉及到整个开源库，所以你想改哪些都可以，因为业务上不一样嘛！
