### ISSUE TITLE
打包提交到app store的问题

### ISSUE THREAD

**Issue by hlm1990** [xhzengAIB/MessageDisplayKit#229]
比如我在MessageDisplayKitWeChatExample里引用了MessageDisplayKit  那 MessageDisplayKitWeChatExample的Build Phases里面肯定有Embed Frameworks  在我提交app store的时候就提示ERROR ITMS-90362 The value for key 'MinimumOSVersion' in bundle is invalid. the minimum value is 8.0. 怎么解决

**Comment by zjszyms** [comment]
你的导航栏高度被隐藏，怎么解决的？

**Comment by xhzengAIB** [comment]
@hlm1990 
你好！ 你可以直接使用pod install用源码，或者你可以直接在这里用源码https://github.com/xhzengAIB/MessageDisplayKit/tree/master/MessageDisplayKit
