### ISSUE TITLE
导航栏被隐藏

### ISSUE THREAD

**Issue by zjszyms** [xhzengAIB/MessageDisplayKit#230]
UINavigationBar 被隐藏部分，只有第一次或者输入框有编辑的情况下，才会隐藏

**Comment by xhzengAIB** [comment]
@zjszyms 
你好！  在Demo上吗？具体怎么操作流程呢？

**Comment by zjszyms** [comment]
@xhzengAIB 
Demo里很正常，我也没找出你在哪设置了参数；
我这个只是创建一个VC，继承XHMessageTableViewController，然后简单的push过来；

创建ChatViewController.h 和 ChatViewController.h
@interface ChatViewController : XHMessageTableViewController

页面跳转:
 ChatViewController *chatViewController = [[ChatViewController alloc] init];
 [self.navigationController pushViewController:chatViewController animated:YES];

**Comment by zjszyms** [comment]
@xhzengAIB 
![Uploading image.png…]()

**Comment by zjszyms** [comment]
刚刚是不小心关掉的，这次真的关了！

这个问题是 项目中使用第三方的防止键盘遮挡的控件（IQKeyBoardManager）导致的；

库本身没有问题，再次感谢大神的帮忙；

**Comment by xhzengAIB** [comment]
@zjszyms  不客气，只要大家能解决问题就好！

**Comment by Hitooo** [comment]
IQKeyBoardManager的确会出现这样的情况，后来我把它删掉了，就解决了这个问题；但是有没有好的KeyBoard库来代替IQKeyBoardManager呢？

**Comment by zjszyms** [comment]
@Hitooo 不用删掉，你禁用就行了！IQKeyBoardManager 可以针对个别页面进行禁用操作的！
