### ISSUE TITLE
点击输入框，键盘把输入框盖住了，而且切换中文输入法，输入框完全被挡在后面了

### ISSUE THREAD

**Issue by meiyua0218sdo** [xhzengAIB/MessageDisplayKit#232]

**Comment by wintersweet123** [comment]
为什么你能运行，我都编译不了呢

**Comment by meiyua0218sdo** [comment]
你看你报什么错误，然后百度

**Comment by wintersweet123** [comment]
我编译了是一点反应都没有，不知道咋回事

**Comment by xhzengAIB** [comment]
![image](https://cloud.githubusercontent.com/assets/1969908/8372564/e74932b0-1c16-11e5-864f-3562837c00e8.png)
