### ISSUE TITLE
layoutOtherMenuViewHiden方法bug？

### ISSUE THREAD

**Issue by haifenghuang** [xhzengAIB/MessageDisplayKit#235]
`XHMessageTableViewController.m`文件中，layoutOtherMenuViewHiden方法中有下面这段语句：  

```objc
        __block CGRect otherMenuViewFrame;
        
        void (^InputViewAnimation)(BOOL hide) = ^(BOOL hide) {
            inputViewFrame.origin.y = (hide ? (CGRectGetHeight(self.view.bounds) - CGRectGetHeight(inputViewFrame)) : (CGRectGetMinY(otherMenuViewFrame) - CGRectGetHeight(inputViewFrame)));
            self.messageInputView.frame = inputViewFrame;
```

其中`(CGRectGetMinY(otherMenuViewFrame)`中的otherMenuViewFrame没有初始化，编译时报警告如下:
`XHMessageTableViewController.m:886:120: Passed-by-value struct argument contains uninitialized data (e.g., via the field chain: 'origin.x')`  
请帮忙解决一下？

**Comment by xhzengAIB** [comment]
那是因为其他空间没有初始化的原因吗？  在Demo里面出现类似你说的警告吗？

**Comment by haifenghuang** [comment]
对，是在运行`MessageDisplayKitWeChatExample`的例子时候，编译期间报告的警告信息

**Comment by xhzengAIB** [comment]
@haifenghuang 
嗯！ 这个你有什么解决思路吗？我的理解应该是View的层次上出现错乱

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/MessageDisplayKit/commit/0a677e966950298b6fd2257ea931ce3752a768d2
