### ISSUE TITLE
在聊天输入框中 粘贴长段的回车比较多的长字段， 会出现很奇葩的问题

### ISSUE THREAD

**Issue by brasbug** [xhzengAIB/MessageDisplayKit#236]
您好，您的认证是打发通过，是打发士大夫会费即可成功认证，名额有限，每年仅开放一万席。

如果您持有万asdfasdfasdfasdf业证书中的一种，即可获得asdfadf仅用于认证会员费用减免）

认证会as阿什利打开附件阿斯利康京东方；阿狸说看见对方了； 金利科技了范德萨家乐福加拉塞克点击  了；卡上的福利就暗示法律的空间  饮消费券，本地化生活消费券，马术、游艇、高尔夫等精选体验。

支付方式：
1.公司账户：交通行）
账号：aashasdhadhfa dfasdfa
名称：啊哈SDHASF等哈说对方 司
2.支付宝账户：asdfasdfasf
3.微信转账：asdfasdfasdf

**Comment by xhzengAIB** [comment]
你好！ 你的意思输入以上文本吗？

**Comment by brasbug** [comment]
对的， 不只是以上文本  其他的只要是大段文本 带有回车比较多的

**Comment by brasbug** [comment]
http://pan.baidu.com/s/1qW7Ndgg     http://pan.baidu.com/s/1pJsWcER   这里是我录 的视频， 你可以看看什么情况

**Comment by duxinxiao** [comment]
你好，我也发现这个问题，只要粘贴过来的文字有一个换行符显示便会出现问题。如果换行符太多就会直接崩溃，而且有时候在没有点发送时会一直发生滚动

**Comment by brasbug** [comment]
@xhzengAIB   我查了好久，没找到问题原因

**Comment by brasbug** [comment]
有木有进展？

**Comment by haifenghuang** [comment]
在`XHMessageBubbleView.m`文件中，方法`neededWidthForText`中有一句是这么写的:  

```objc
temp = [[array objectAtIndex:i] sizeWithFont:[[XHMessageBubbleView appearance] font] constrainedToSize:CGSizeMake(MAXFLOAT, 20)];
```  

其中的`CGSizeMake(MAXFLOAT,20)`是否应该更改成`CGSizeMake(20, MAXFLOAT)`?  
我认为MAXFLOAT应该是第二个参数，而不是第一个参数。

**Comment by xhzengAIB** [comment]
Hi！@haifenghuang 
你测试过有没有问题啊？

**Comment by xhzengAIB** [comment]
@haifenghuang 
你理解错了，这个只是用来计算，然后判断动态宽度的意思

**Comment by haifenghuang** [comment]
不好意思，确实是我理解错了

**Comment by xhzengAIB** [comment]
![nobug](https://cloud.githubusercontent.com/assets/1969908/8469230/aa187dd2-20a9-11e5-8634-29a45772d989.gif)

**Comment by brasbug** [comment]
thks 请问是修复的那部分代码？

**Comment by brasbug** [comment]
问题依然没有解决哦   这段话有时候能输入 输入大段带有回车的比较多的长文字还是会出现

**Comment by xhzengAIB** [comment]
@brasbug 
没有改任何代码

**Comment by xhzengAIB** [comment]
最近修改的都没有和这个相关的哦！  你现在使用的代码是不是久的啊？

**Comment by brasbug** [comment]
我使用这里最新的代码测试也是一样的，

**Comment by brasbug** [comment]
复制上面文本  粘贴进去

**Comment by brasbug** [comment]
@duxinxiao  你也来描述下这个问题，可能我的描述并不准确

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/MessageDisplayKit/blob/master/Example/MessageDisplayKitWeChatExample/MessageDisplayKitWeChatExample/Controllers/XHDemoWeChatMessageTableViewController/XHDemoWeChatMessageTableViewController.m#L31

在这里，把你的文本粘帖到这里，然后再展示，我是这么操作的，没有问题呢！

**Comment by lzwjava** [comment]
![leanchatbug](https://cloud.githubusercontent.com/assets/5022872/8474746/ef2d1082-20e4-11e5-9f76-8690ebb7a3e4.gif)

我这边也没问题。

**Comment by xhzengAIB** [comment]
@lzwjava 
需要问一下他的SDK版本是多少

**Comment by lzwjava** [comment]
不是，有问题啊。把上面的那段文本，通过文件传输助手发送给微信，然后用真机运行MDK，从微信里复制粘贴过来。MDK 没有反应，然后，强杀，点击桌面图标无反应。只能重启了。

**Comment by lzwjava** [comment]
我上面给的gif 不是楼主的文本，所以没问题。

**Comment by xhzengAIB** [comment]
@lzwjava 
你调试看看，卡死在哪里呢？

**Comment by xhzengAIB** [comment]
@lzwjava 
添加一个全局的断点，这样就知道死在什么地方？

**Comment by lzwjava** [comment]
整个卡死，xcode 也没响应。

@xhzengAIB

**Comment by lzwjava** [comment]
很有意思，我这边

```

您好，您的认证是打发通过，是打发士大夫会费即可成功认证，名额有限，每年仅开放一万席。

如果您持有万asdfasdfasdfasdf业证书中的一种，即可获得asdfadf仅用于认证会员费用减免）

认证会as阿什利打开附件阿斯利康京东方；阿狸说看见对方了； 金利科技了范德萨家乐福加拉塞克点击 了；卡上的福利就暗示法律的空间 饮消费券，本地化生活消费券，马术、游艇、高尔夫等精选体验。

支付方式：
```
上面文本卡死。



```

您好，您的认证是打发通过，是打发士大夫会费即可成功认证，名额有限，每年仅开放一万席。

如果您持有万asdfasdfasdfasdf业证书中的一种，即可获得asdfadf仅用于认证会员费用减免）

认证会as阿什利打开附件阿斯利康京东方；阿狸说看见对方了； 金利科技了范德萨家乐福加拉塞克点击 了；卡上的福利就暗示法律的空间 饮消费券，本地化生活消费券，马术、游艇、高尔夫等精选体验。

```

去掉最后一行，这样就没问题。

**Comment by xhzengAIB** [comment]
why？

**Comment by brasbug** [comment]
我猜 文本里的回车好像做了什么东西  应该是陷入死循环了
