### ISSUE TITLE
关于二维码识别的部分

### ISSUE THREAD

**Issue by Yrocky** [xhzengAIB/MessageDisplayKit#237]
微信中有进行摄像头识别二维码和本地图片识别二维码两种功能，识别本地图片中的二维码是如何实现的？没有思路

**Comment by xhzengAIB** [comment]
你好！
在我技术范畴内的理解：
第一：摄像头的识别，可以在iOS SDK基础上解决，也可以在ZBar上解决，原理大概是一致的，就是获取摄像头的视频数据，从而得到一张图的信息，接下来就是识别的流程。
第二：识别图片中的二维码，在上述的原理中，你可以知道，其实都是通过一张图片去辨别图片所承载的信息，所以可以通过ZBar的附带API，从而解决识别的问题。

希望对你有帮助

我得关闭这个Issue了

**Comment by hlm1990** [comment]
意思是界面可以用你的界面 但是识别要用ZBar的api来实现是吗
