### ISSUE TITLE
更改BubbleView的字体颜色

### ISSUE THREAD

**Issue by haifenghuang** [xhzengAIB/MessageDisplayKit#246]
能否提供API来更改BubbleView的发送和接收的字体颜色，而且Sending和Receiving方的字体颜色不同。如果说提供API比较困难，那么能否告知在哪里能够更改？

**Comment by xhzengAIB** [comment]
这个已经有直接的Delegate了

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/MessageDisplayKit/blob/master/Example/MessageDisplayKitWeChatExample/MessageDisplayKitWeChatExample/Controllers/XHDemoWeChatMessageTableViewController/XHDemoWeChatMessageTableViewController.m#L428
