### ISSUE TITLE
文字单元格的laytou有问题

### ISSUE THREAD

**Issue by qzc77** [xhzengAIB/MessageDisplayKit#248]
BubbleView的layout有点小问题，我修改如下后正常了！
case XHBubbleMessageMediaTypeText:
        case XHBubbleMessageMediaTypeVoice:
        case XHBubbleMessageMediaTypeEmotion: {
            self.bubbleImageView.frame = bubbleFrame;
            
            CGFloat textX = CGRectGetMinX(bubbleFrame) + kTextHorizontalBubblePadding;
            
            if (self.message.bubbleMessageType == XHBubbleMessageTypeReceiving) {
                textX += kXHArrowMarginWidth;
            }
            
            CGRect textFrame = CGRectMake(textX,
                                          CGRectGetMinY(bubbleFrame) + kTextMarginTop,
                                          CGRectGetWidth(bubbleFrame) - kTextHorizontalBubblePadding * 2 - kXHArrowMarginWidth,
                                          bubbleFrame.size.height - kTextMarginTop - kTextMarginBottom);
            
            self.displayTextView.frame = CGRectIntegral(textFrame);

**Comment by xhzengAIB** [comment]
@qzc77 
感谢，能否PR给我呢？

Jack

**Comment by qzc77** [comment]
PR没用过哈？我看看咋玩，最近赶进度加了些功能，代码有些凌乱，8月份整理一下了发给你！

**Comment by xhzengAIB** [comment]
你这里最主要修改了什么呢？我来整理也可以

**Comment by xhzengAIB** [comment]
仅仅对BubbleView的layout的问题

**Comment by qzc77** [comment]
1、发送，重发
2、文件类型
3、系统消息类型（谁邀请了谁谁）
4、一些bug修改

**Comment by qzc77** [comment]
发送主要是菊花，其实图片或者语音上传进度加上更好

**Comment by xhzengAIB** [comment]
是的！  我在issue里面有计划，都是忙了   没有时间搞

**Comment by qzc77** [comment]
5、图片上传可以一次传多个，改用了QBIMagePicket
6、图片详情也顺便用QBImage做了多图预览

**Comment by xhzengAIB** [comment]
:+1:

**Comment by qzc77** [comment]
哈，可惜你在广州，要在深圳就一起过来搞，我们做企业管理软件。

**Comment by qzc77** [comment]
现在代码是你去年的分支上搞的，等稍微空闲了我合并到你最新代码去

**Comment by xhzengAIB** [comment]
那你先忙吧！  期待你的PR

**Comment by xhzengAIB** [comment]
@qzc77 
你好！在吗？你说文本的frame算不对，是修改哪里啊？

Jack

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/MessageDisplayKit/blob/master/MessageDisplayKit/Classes/Views/MessageContentViews/XHMessageBubbleView.m#L418

我现在已经是这样的，你是怎么修改的呢？

**Comment by qzc77** [comment]
@xhzengAIB 那应该对了，我是用你去年的代码，看样子我们两改的方式一样！
另外昨天发现一个问题，现在你最新的代码kTextHorizontalBubblePending统一左右边距都是16，真实显示的时候，右边会出现留白大于16（正好显示文字换行），我现在的处理办法是
#define kTextHorizontalBubblePaddingLeft 12.0f
#define kTextHorizontalBubblePaddingRight 8.0f
这样UI显示会更合理，你有更好的方式请赐教！

**Comment by lzwjava** [comment]
@qzc77 能否截图看看留白情况？我这里应该修正了，https://github.com/xhzengAIB/MessageDisplayKit/pull/241
