### ISSUE TITLE
图片尺寸比例问题有啥好办法？

### ISSUE THREAD

**Issue by qzc77** [xhzengAIB/MessageDisplayKit#249]
现在图片强制按120*120显示，大部分图片显示比例不对，
我用image的真实尺寸计算后是能解决问题。
但是带来另外一个问题，图片未下载的情况，尺寸会先固定120*120，等到图片下载完以后，强制重新重绘cell好像也是有些问题。。

**Comment by xhzengAIB** [comment]
你需要充值reload某一个Cell，这样的高度才能同步改变，QQ是这么做的

**Comment by qzc77** [comment]
是的，可是现在代码从XHBubblePhotoImageView触发到tableview的reload，写了后感觉代码非常不爽快。

**Comment by xhzengAIB** [comment]
通过Delegate来操作，微信的话，是在发送和接受就已经知道图片的size，所以看你采取什么策略

**Comment by qzc77** [comment]
是的，我刚才的想法也是服务端把size给到客户端，这样更容易处理
