### ISSUE TITLE
你这个demo要安装cocopods才能打开吗

### ISSUE THREAD

**Issue by ssssssun** [xhzengAIB/MessageDisplayKit#251]
我直接打开的话，会有"_OBJC_CLASS_$_LKBadgeView", referenced from:
      objc-class-ref in UIView+XHBadgeView.o
  "_OBJC_CLASS_$_SETextView", referenced from:
      objc-class-ref in XHAlbumRichTextView.o
  "_OBJC_CLASS_$_XHAudioPlayerHelper", referenced from:
      objc-class-ref in XHDemoWeChatMessageTableViewController.o
  "_OBJC_CLASS_$_XHCacheManager", referenced from:
      objc-class-ref in XHStoreManager.o
  "_OBJC_CLASS_$_XHCaptureHelper", referenced from:
      objc-class-ref in XHQRCodeViewController.o
  "_OBJC_CLASS_$_XHDisplayLocationViewController", referenced from:
      objc-class-ref in XHDemoWeChatMessageTableViewController.o
  "_OBJC_CLASS_$_XHDisplayMediaViewController", referenced from:
错误，我是新手，想求教下，

**Comment by xhzengAIB** [comment]
https://github.com/JackTeam/XHNewsFrameworkExample/blob/master/fixTheHeadError.gif

**Comment by ssssssun** [comment]
能发份你最新的一份代码吗，我下载的好像是很久之前的，谢谢了

**Comment by xhzengAIB** [comment]
直接在这里下载就可以了哦！
