### ISSUE TITLE
如果以超级快的速度发信息的话，在iphone5在CPU会高达80-100%

### ISSUE THREAD

**Issue by chenzhijie** [xhzengAIB/MessageDisplayKit#254]
请问，这个是正常的吗？或者有啥办法优化吗

**Comment by xhzengAIB** [comment]
在这样的情况下，我还没有做到详细的性能测试，你估计是什么问题呢？

Jack

**Comment by chenzhijie** [comment]
我猜测是reloadData频繁的话，ui方面很多重绘。如果多个人频繁刷屏，估计就吃不消了

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/MessageDisplayKit/blob/master/MessageDisplayKit/Classes/Controllers/XHMessageTableViewController/XHMessageTableViewController.m#L256
但是这里只有Insert的刷新，没有调用reloadData方法来刷新，这样应该不会刷新所有Cell的！
你觉得还有别的问题吗？

**Comment by xhzengAIB** [comment]
讨论一下，或许我们就一起解决了，这样性能问题是一定得要解决的bug

**Comment by chenzhijie** [comment]
https://github.com/xhzengAIB/MessageDisplayKit/blob/master/MessageDisplayKit/Classes/Controllers/XHMessageTableViewController/XHMessageTableViewController.m#L237

是每次接受到消息会调用 addMessage 然后就会reloadData

**Comment by chenzhijie** [comment]
每次增加一个cell 会计算到bubble的文本的高度，然后配置cell各个subview的frame. 我曾在instrument 的time profiler测试到 貌似比较费时间是那个 XHMessageBubbleView.m的getBubbleFrameWithMessage

**Comment by chenzhijie** [comment]
不过我试过用NSCache缓存cell的高度 貌似没什么卵用。。用微信同样高频率发消息的话 i6和i6plus都会卡住
