### ISSUE TITLE
求解 在发送图片时  我发送成功了  屏幕不显示图片 但是点击图片 放大了有显示了 然后报错

### ISSUE THREAD

**Issue by zhang1104094894** [xhzengAIB/MessageDisplayKit#257]
报错内容<Error>: CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 32 bits/pixel; 3-component color space; kCGImageAlphaLast; 1120 bytes/row.
Aug 28 10:06:41 31239623053123962305deMac-mini.local ZZChatiPhone[1992] <Error>: CGContextConcatCTM: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Aug 28 10:06:41 31239623053123962305deMac-mini.local ZZChatiPhone[1992] <Error>: CGContextSetInterpolationQuality: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Aug 28 10:06:41 31239623053123962305deMac-mini.local ZZChatiPhone[1992] <Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Aug 28 10:06:41 31239623053123962305deMac-mini.local ZZChatiPhone[1992] <Error>: CGBitmapContextCreateImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
2015-08-28 10:06:43.103 ZZChatiPhone[1992:53269] -[ChatRoomMessageViewController multiMediaMessageDidSelectedOnMessage:atIndexPath:onMessageTableViewCell:] [Line 313] message : <UIImage: 0x7fbf829bf4b0>, {54.5, 54.5}

**Comment by xhzengAIB** [comment]
@zhang1104094894 
这个应该是同一个问题
