### ISSUE TITLE
代码太凌乱了 不晓得结构分层是怎么分的 完全像个新手的写的

### ISSUE THREAD

**Issue by applejian** [xhzengAIB/MessageDisplayKit#260]
代码太凌乱了 不晓得结构分层是怎么分的 完全像个新手的写的 功能模块多而不精 弄好几个简单基本的功能就可以

**Comment by zhang1104094894** [comment]
你才是新手呢   支持XH

**Comment by xhzengAIB** [comment]
@applejian 
可以接受你的意见，但是你说代码凌乱，结构不清晰，能否具体描述一下？方便我这边做出相应的改进。

麻烦你把问题描述清楚，如果大家觉得ok，我们会继续改进的。

Jack

**Comment by lzwjava** [comment]
支持 XH & love XH
