### ISSUE TITLE
发现问题 ：就是消息和消息框大小适配  有时候有问题，我不知道其他人遇到没有

### ISSUE THREAD

**Issue by Ewithome** [xhzengAIB/MessageDisplayKit#265]
![bdaxr6 nc3 aw b f4snm](https://cloud.githubusercontent.com/assets/8252464/9753420/09fa336e-56ef-11e5-96f9-6719e039488e.jpg)
![24b7 hkfggtgk xlv90jk](https://cloud.githubusercontent.com/assets/8252464/9753422/0ae04d4a-56ef-11e5-804b-49645fc6bced.jpg)
这个是不是那里有问题啊

**Comment by zhang1104094894** [comment]
![24b7 hkfggtgk xlv90jk](https://cloud.githubusercontent.com/assets/8252464/9753442/628f67ce-56ef-11e5-9a2e-0726816e1b73.jpg)
![Uploading 619A6E51-34B1-43DB-9D86-1B37C0F23E80.png…]()

**Comment by zhang1104094894** [comment]
还有在github 上看  到4.4版本了  但是在pod记载的时候怎么还是4.2 啊   不是没有更新啊 
![59b30ac7-1466-4454-af63-f25c98573d83](https://cloud.githubusercontent.com/assets/8252464/9753459/b2b188b8-56ef-11e5-8b81-76d8437a4fb6.png)

**Comment by alexliubj** [comment]
输入hey hey 或者 hey 或者英文，在最新版本貌似会有问题。
