### ISSUE TITLE
[Crash] this line  :  self.shareMenuScrollView.delegate = self; EXC_BAD_Instruction

### ISSUE THREAD

**Issue by alexliubj** [xhzengAIB/MessageDisplayKit#267]
objc[5776]: Cannot form weak reference to instance (0x7f836349cd80) of class XHShareMenuView. It is possible that this object was over-released, or is in the process of deallocation.
(lldb)

**Comment by xhzengAIB** [comment]
Hi! @alexliubj 

Under what circumstances appear crash?

Jack

**Comment by AustinChou** [comment]
Experiencing the same problem here. 
@xhzengAIB When leaving the chat view controller, it crashes
Base SDK: 9.0
Build System: El Capitan

**Comment by alexliubj** [comment]
这个错误之前有些低级啊。。。 - (void)dealloc {
-    self.shareMenuScrollView.delegate = self;
