### ISSUE TITLE
Storyboard bug？

### ISSUE THREAD

**Issue by alexliubj** [xhzengAIB/MessageDisplayKit#268]
使用Storyboard 
直接拖拽一个UIViewcontroller，然后类型是：XHDemoWeChatMessageTableViewController

发现kit 库里面很多图片都找不到，无法显示正常。怎么解决？

**Comment by alexliubj** [comment]
类似资源都无法找到。例如：face@2x

**Comment by alexliubj** [comment]
使用方法，直接cocoapods，然后复制粘贴：XHDemoWeChatMessageTableViewController
在之后就直接用了，找不到所有pods 里面的资源图片。只有单独拆出来拿到主项目才行。

**Comment by xhzengAIB** [comment]
@alexliubj 
你可以看到这些自定义参数，内部的资源和外部没有任何关系了。
https://github.com/xhzengAIB/MessageDisplayKit/commit/8c3c320d59dd07d8d5c137f2650d0f2e9be30ea2

**Comment by alexliubj** [comment]
什么意思？现在是找不到图片呀，不是说自定义的问题。现在所有通过pods 引入的library图片都找不到。需要在本工程添加才可以的。pods 的你的自带图片都找不到。都不显示。

**Comment by xhzengAIB** [comment]
首先，XHDemoWeChatMessageTableViewController这个只是一个Demo，
再者face这个资源文件可以外部定义，怎么定义看这里哦！https://github.com/xhzengAIB/MessageDisplayKit/commit/8c3c320d59dd07d8d5c137f2650d0f2e9be30ea2
