### ISSUE TITLE
希望XH看看怎么回事，求解决

### ISSUE THREAD

**Issue by Ewithome** [xhzengAIB/MessageDisplayKit#269]
![4de vlric55w9 8 a2 _ m](https://cloud.githubusercontent.com/assets/8252464/9843594/7921c3d0-5aee-11e5-85ca-e8bbcb3ceae6.jpg)
![a5a60217-11f1-42f9-ae11-88d85981c3e6](https://cloud.githubusercontent.com/assets/8252464/9843604/873194d2-5aee-11e5-97fe-b42f42822843.png)

**Comment by xhzengAIB** [comment]
你好！  这个问题仅仅是qc吗？你有什么好的办法？

**Comment by Ewithome** [comment]
不是，我遇到好几次了  我看你写的代码了  我没想好的方法呢 我感觉是算得那里有问题

**Comment by Ewithome** [comment]
很有可能是换行的问题    换行

**Comment by Ewithome** [comment]
![c62fb3f9-cb23-45b1-a88e-6959afc7bae3](https://cloud.githubusercontent.com/assets/8252464/9847222/056e9956-5b0a-11e5-8a85-70beded3028c.png)
就是换行的问题  你看在在处理换行问题那里的算法

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/MessageDisplayKit/blob/master/MessageDisplayKit/Classes/Views/MessageContentViews/XHMessageBubbleView.m#L59

**Comment by xhzengAIB** [comment]
在这里

**Comment by Ewithome** [comment]
sizeWithFont   constrainedToSize  这个方法8 不能用了

**Comment by xhzengAIB** [comment]
@Ewithome 
需要怎么解决一下呢？
刚才我试了一下，确实是有问题的

**Comment by alexliubj** [comment]
对，有次问题。

**Comment by xhzengAIB** [comment]
Hi! @Ewithome 

这个问题能否帮忙解决一下？

**Comment by Ewithome** [comment]
我现在还不知道怎么解决，不过我会看怎么解决的，有方法了，我会和你说的

**Comment by xhzengAIB** [comment]
@Ewithome 
Thanks!
