### ISSUE TITLE
显示空白

### ISSUE THREAD

**Issue by zzStar** [xhzengAIB/MessageDisplayKit#272]
![image](https://cloud.githubusercontent.com/assets/7801496/9933230/10affd18-5d7c-11e5-8136-ab7f2a8325e1.png)
swift项目 通过cocoa pod 引用：
pod 'MessageDisplayKit'
好像 键盘和素材不显示。

**Comment by xhzengAIB** [comment]
你好！你可以通过这个来定制这些图标，素材是外部自定义的，你可以直接添加进去。https://github.com/xhzengAIB/MessageDisplayKit/blob/master/MessageDisplayKit/Classes/Common/XHConfigurationHelper.h#L12
