### ISSUE TITLE
IOS9 发送文本消息 丢失最后一个字符

### ISSUE THREAD

**Issue by zzStar** [xhzengAIB/MessageDisplayKit#276]
IOS9 发送文本消息时，界面显示 会丢失最后一个字符！
1.中英文混合，中文在前，英文在后。英文不显示。
2.中英文混合，英文在前，中文在后。最后一个中文字符不显示。
2.纯英文，英文最后一个字母不显示。

**Comment by xhzengAIB** [comment]
你好！  这个问题已经修复了，请pod update一下哈！

**Comment by alexliubj** [comment]
输入 hey jude 不行，刚试的。。ref 一下那个文件是修正这个问题的？

**Comment by zzStar** [comment]
@xhzengAIB 
问题依旧，没有解决哦？

**Comment by alexliubj** [comment]
Contact  abcd@abcd.com 也不会显示全？
