### ISSUE TITLE
编译报错，说是NSFont冲突 了

### ISSUE THREAD

**Issue by zhuweiDark** [xhzengAIB/MessageDisplayKit#280]
Build target MessageDisplayFramework of project MessageDisplayExample with configuration Debug

ProcessInfoPlistFile /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Products/Debug-iphoneos/MessageDisplayFramework.framework/Versions/A/Resources/Info.plist MessageDisplayFramework/MessageDisplayFramework-Info.plist
    cd /Users/zhuwei/Downloads/MessageDisplayKit-master/Example/MessageDisplayExample
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-infoPlistUtility /Users/zhuwei/Downloads/MessageDisplayKit-master/Example/MessageDisplayExample/MessageDisplayFramework/MessageDisplayFramework-Info.plist -expandbuildsettings -format binary -platform iphoneos -o /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Products/Debug-iphoneos/MessageDisplayFramework.framework/Versions/A/Resources/Info.plist

ProcessPCH /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/PrecompiledHeaders/MessageDisplayFramework-Prefix-acmqxhqlaregihdzhvtpdxqhgszr/MessageDisplayFramework-Prefix.pch.pch MessageDisplayFramework/MessageDisplayFramework-Prefix.pch normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/zhuwei/Downloads/MessageDisplayKit-master/Example/MessageDisplayExample
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c-header -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/zhuwei/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/zhuwei/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=6.0 -g -Wno-sign-conversion -fembed-bitcode-marker -iquote /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-generated-files.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-own-target-headers.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-all-target-headers.hmap -iquote /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-project-headers.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Products/Debug-iphoneos/include -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/DerivedSources/armv7 -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/DerivedSources -F/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Products/Debug-iphoneos -MD -MT dependencies -MF /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/PrecompiledHeaders/MessageDisplayFramework-Prefix-acmqxhqlaregihdzhvtpdxqhgszr/MessageDisplayFramework-Prefix.pch.d -c /Users/zhuwei/Downloads/MessageDisplayKit-master/Example/MessageDisplayExample/MessageDisplayFramework/MessageDisplayFramework-Prefix.pch -o /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/PrecompiledHeaders/MessageDisplayFramework-Prefix-acmqxhqlaregihdzhvtpdxqhgszr/MessageDisplayFramework-Prefix.pch.pch --serialize-diagnostics /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/PrecompiledHeaders/MessageDisplayFramework-Prefix-acmqxhqlaregihdzhvtpdxqhgszr/MessageDisplayFramework-Prefix.pch.dia

CompileC /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/XHAlbumCollectionViewFlowLayout.o /Users/zhuwei/Downloads/MessageDisplayKit-master/MessageDisplayKit/Classes/Views/AlbumContentViews/XHAlbumCollectionViewFlowLayout.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/zhuwei/Downloads/MessageDisplayKit-master/Example/MessageDisplayExample
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/zhuwei/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/zhuwei/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=6.0 -g -Wno-sign-conversion -fembed-bitcode-marker -iquote /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-generated-files.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-own-target-headers.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-all-target-headers.hmap -iquote /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-project-headers.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Products/Debug-iphoneos/include -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/DerivedSources/armv7 -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/DerivedSources -F/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Products/Debug-iphoneos -include /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/PrecompiledHeaders/MessageDisplayFramework-Prefix-acmqxhqlaregihdzhvtpdxqhgszr/MessageDisplayFramework-Prefix.pch -MMD -MT dependencies -MF /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/XHAlbumCollectionViewFlowLayout.d --serialize-diagnostics /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/XHAlbumCollectionViewFlowLayout.dia -c /Users/zhuwei/Downloads/MessageDisplayKit-master/MessageDisplayKit/Classes/Views/AlbumContentViews/XHAlbumCollectionViewFlowLayout.m -o /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/XHAlbumCollectionViewFlowLayout.o

CompileC /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/XHDisplayEmotionViewController.o /Users/zhuwei/Downloads/MessageDisplayKit-master/MessageDisplayKit/Classes/Controllers/XHMessageTableViewController/XHDisplayEmotionViewController/XHDisplayEmotionViewController.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/zhuwei/Downloads/MessageDisplayKit-master/Example/MessageDisplayExample
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/zhuwei/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/zhuwei/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=6.0 -g -Wno-sign-conversion -fembed-bitcode-marker -iquote /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-generated-files.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-own-target-headers.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-all-target-headers.hmap -iquote /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-project-headers.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Products/Debug-iphoneos/include -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/DerivedSources/armv7 -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/DerivedSources -F/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Products/Debug-iphoneos -include /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/PrecompiledHeaders/MessageDisplayFramework-Prefix-acmqxhqlaregihdzhvtpdxqhgszr/MessageDisplayFramework-Prefix.pch -MMD -MT dependencies -MF /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/XHDisplayEmotionViewController.d --serialize-diagnostics /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/XHDisplayEmotionViewController.dia -c /Users/zhuwei/Downloads/MessageDisplayKit-master/MessageDisplayKit/Classes/Controllers/XHMessageTableViewController/XHDisplayEmotionViewController/XHDisplayEmotionViewController.m -o /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/XHDisplayEmotionViewController.o

CompileC /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/SETextLayout.o /Users/zhuwei/Downloads/MessageDisplayKit-master/MessageDisplayKit/Classes/Vendor/SECoreTextView/SETextLayout.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/zhuwei/Downloads/MessageDisplayKit-master/Example/MessageDisplayExample
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/zhuwei/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/zhuwei/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=6.0 -g -Wno-sign-conversion -fembed-bitcode-marker -iquote /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-generated-files.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-own-target-headers.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-all-target-headers.hmap -iquote /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-project-headers.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Products/Debug-iphoneos/include -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/DerivedSources/armv7 -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/DerivedSources -F/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Products/Debug-iphoneos -include /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/PrecompiledHeaders/MessageDisplayFramework-Prefix-acmqxhqlaregihdzhvtpdxqhgszr/MessageDisplayFramework-Prefix.pch -MMD -MT dependencies -MF /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/SETextLayout.d --serialize-diagnostics /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/SETextLayout.dia -c /Users/zhuwei/Downloads/MessageDisplayKit-master/MessageDisplayKit/Classes/Vendor/SECoreTextView/SETextLayout.m -o /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/SETextLayout.o

In file included from /Users/zhuwei/Downloads/MessageDisplayKit-master/MessageDisplayKit/Classes/Vendor/SECoreTextView/SETextLayout.m:9:
In file included from /Users/zhuwei/Downloads/MessageDisplayKit-master/MessageDisplayKit/Classes/Vendor/SECoreTextView/SETextLayout.h:11:
/Users/zhuwei/Downloads/MessageDisplayKit-master/MessageDisplayKit/Classes/Vendor/SECoreTextView/SECompatibility.h:15:22: error: conflicting types for alias 'NSFont'
@compatibility_alias NSFont UIFont;
                     ^
In module 'CoreText' imported from /Users/zhuwei/Downloads/MessageDisplayKit-master/MessageDisplayKit/Classes/Vendor/SECoreTextView/SETextLayout.h:10:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTDefines.h:60:8: note: previous declaration is here
@class NSFont;
       ^
1 error generated.

CompileC /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/UIImage+Utility.o /Users/zhuwei/Downloads/MessageDisplayKit-master/MessageDisplayKit/Classes/Categorys/UIImage/UIImage+Utility.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/zhuwei/Downloads/MessageDisplayKit-master/Example/MessageDisplayExample
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/zhuwei/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/zhuwei/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=6.0 -g -Wno-sign-conversion -fembed-bitcode-marker -iquote /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-generated-files.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-own-target-headers.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-all-target-headers.hmap -iquote /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/MessageDisplayFramework-project-headers.hmap -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Products/Debug-iphoneos/include -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/DerivedSources/armv7 -I/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/DerivedSources -F/Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Products/Debug-iphoneos -include /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/PrecompiledHeaders/MessageDisplayFramework-Prefix-acmqxhqlaregihdzhvtpdxqhgszr/MessageDisplayFramework-Prefix.pch -MMD -MT dependencies -MF /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/UIImage+Utility.d --serialize-diagnostics /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/UIImage+Utility.dia -c /Users/zhuwei/Downloads/MessageDisplayKit-master/MessageDisplayKit/Classes/Categorys/UIImage/UIImage+Utility.m -o /Users/zhuwei/Library/Developer/Xcode/DerivedData/MessageDisplayExample-dvurdadftfjofdeudvaijghgsgzd/Build/Intermediates/MessageDisplayExample.build/Debug-iphoneos/MessageDisplayFramework.build/Objects-normal/armv7/UIImage+Utility.o

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/MessageDisplayKit/issues/189
