### ISSUE TITLE
为什么我打开程序就显示错误，在SECompatibility.h里面的方法名@compatibility_alias NSFont UIFont;

### ISSUE THREAD

**Issue by xiaogouzai27** [xhzengAIB/MessageDisplayKit#295]
为什么我打开程序就显示错误，在SECompatibility.h里面的方法名@compatibility_alias NSFont UIFont;
错误显示Conflicting types for alias 'NSFond'

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/MessageDisplayKit/issues/209
