### ISSUE TITLE
 现在是不管了是吧

### ISSUE THREAD

**Issue by jcxc** [xhzengAIB/MessageDisplayKit#320]
这。。。。

**Comment by xhzengAIB** [comment]
@jcxc 非常感谢你提醒了我，我打算在五一期间整理大家的问题，然后统一进行修复，希望我没有让你失望，好嘛！

Jack

**Comment by jcxc** [comment]
谢谢～～～

**Comment by xhzengAIB** [comment]
请关注这个Issue吧！https://github.com/xhzengAIB/MessageDisplayKit/issues/321
